; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
framework = arduino
board = teensy41

; Additional config requirements:
; https://community.platformio.org/t/how-to-modify-teensy-core-files/7425/5
; Change USB speed from 480 to 12 Mbps by uncommenting the line in:
; https://github.com/PaulStoffregen/cores/blob/master/teensy4/usb.c
; Needs to be reimplemented after updating the Teensy PlatformIO package.